### ISSUE TITLE
can not download data landsat 8

### ISSUE THREAD

**Issue by polzader** [olivierhagolle/LANDSAT-Download#15]
Hi

I am try download:
python download_landsat_scene.py -o scene -b LC8 -d 20150524 -s 229082 -u usgs.txt -p proxy.txt --output /home/pablo/landsat/

this raise error:

None None
Establishing connection to Earthexplorer with proxy...
Traceback (most recent call last):
  File "download_landsat_scene.py", line 564, in <module>
    main()
  File "download_landsat_scene.py", line 382, in main
    connect_earthexplorer_proxy(proxy,usgs)
  File "download_landsat_scene.py", line 40, in connect_earthexplorer_proxy
    f = opener.open('https://earthexplorer.usgs.gov/login', params)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

I am usiging Ubuntu 12.04 LTS.

Thanks

**Comment by olivierhagolle** [comment]
Dear Polzader,
sorry for that. Did you configure your proxy parameters correctly ?
As I only tested the software behind CNES proxy or with no proxy, I am not sure it works anywhere. 
But the most probable is some errors in the proxy.txt or usgs.txt files that you need to configure.
Olivier
