### ISSUE TITLE
After USGS site maintenance, code no longer works

### ISSUE THREAD

**Issue by blbates** [olivierhagolle/LANDSAT-Download#16]
Brad-Batess-MacBook-Pro:Landsat_Data bradbates$ python download_landsat_scene.py -o scene -b LC8 -d 20150526 -f 20150601 -s 029033 -u usgs.txt --output  /Users/bradbates/Desktop/Landsat_Data/Landsat_8
None None
Establishing connection to Earthexplorer...
Traceback (most recent call last):
  File "download_landsat_scene.py", line 564, in <module>
    main()
  File "download_landsat_scene.py", line 384, in main
    connect_earthexplorer_no_proxy(usgs)	
  File "download_landsat_scene.py", line 58, in connect_earthexplorer_no_proxy
    f = opener.open("https://earthexplorer.usgs.gov/login/", params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by blbates** [comment]
I just solved it. USGS changed their URL on June 30 2015. I think you have to change the login URL in the "download_landsat_scene.py" in all instances. The new URL is https://ers.cr.usgs.gov/login/.

**Comment by olivierhagolle** [comment]
That was a quick fix. Thanks brad !

**Comment by blbates** [comment]
Olivier,

Your program as saved me so much time! Thank you so much.

Brad

**Comment by vascobnunes** [comment]
Just found the same issue.
Thank you Brad..
Oliver, can you make a new release with this, please?

**Comment by olivierhagolle** [comment]
I just committed the correction, sorry for keeping you waiting.

**Comment by vascobnunes** [comment]
You still need to correct all 'http://earthexplorer.usgs.gov' entries like this one:
https://github.com/olivierhagolle/LANDSAT-Download/blob/master/download_landsat_scene.py#L420

**Comment by olivierhagolle** [comment]
Strange, 
I had tested this version and a download worked, while after changing as you suggest it does not work. I tested with LANDSAT 8, with the command line in the readme file.
Could you please repeat this test ?

I have to go and will finish that tomorrow
Regards,
Olivier

**Comment by vascobnunes** [comment]
you're right, nevermind that last comment (was based on wrong assumption I had from running the tool in a remote environment with other problems involved...) :/
sorry...
:)

**Comment by FabianVista** [comment]
For further clarification, because I had trouble with this:
Only the  'http://earthexplorer.usgs.gov/Login' URLs need to be changed, not the ..../download/...
