### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by kalxas** [olivierhagolle/LANDSAT-Download#37]
Anyone else seeing this error?

```
Downloading LE71840332017098NSG00.tar.gz (248.8 MB):
Traceback (most recent call last):
  File "download_landsat_scene.py", line 592, in <module>
    main()
  File "download_landsat_scene.py", line 587, in main
    downloadChunks(url,rep+'/'+site,produit+'.tar.gz')
  File "download_landsat_scene.py", line 135, in downloadChunks
    sizeof_fmt((downloaded // (time.clock() - start)) / 8)))
ZeroDivisionError: float divmod()

```

**Comment by olivierhagolle** [comment]
Hi Kaixas, could you please provide your command line ?
Thanks
Olivier
