### ISSUE TITLE
urllib2 Error

### ISSUE THREAD

**Issue by Digdgeo** [olivierhagolle/LANDSAT-Download#52]
Hi, 

I am trying to run the code to download some landsat scenes but get this errors:

```
Establishing connection to Earthexplorer with proxy...
Traceback (most recent call last):
  File "download_landsat_scene.py", line 592, in <module>
    main()
  File "download_landsat_scene.py", line 410, in main
    connect_earthexplorer_proxy(proxy,usgs)
  File "download_landsat_scene.py", line 37, in connect_earthexplorer_proxy
    data=urllib2.urlopen("https://earthexplorer.usgs.gov/").read()
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/root/anaconda3/envs/py2/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```
I have hanged from http://ers.cr.usgs.gov/ to http://earthexplorer.usgs.gov/ like you said in the post, but always get the same error. Appreciate your help.

Best regards

**Comment by olivierhagolle** [comment]
Hi,
are you really using a proxy ? Are your identifiers OK for proxy,? . Better strore them in the http_proxy variable, and use the function with no proxy.

I have not been downlaoding Landsat data for while, but maybe the shutdown was an issue too.

best regards,
Olivier

**Comment by jinkaizhang** [comment]
i got the similar problem from yesterday. it has been  working fine until yesterday. below is the screen shot. not sure if the USGS is change something.

_download_landsat_scene.py -z unzip -o scene -u usgs.txt -b LC8  -d 20190710 -f 20190712 --output D:\project_workspace\fire_satellite_data\landsat\2019_7_11  -s 047020_

None None
Traceback (most recent call last):
  File "U:\gis_jinkai\RS_landsat_related\landsat_auto_download\python\download_landsat_scene.py", line 592, in <module>
    main()
  File "U:\gis_jinkai\RS_landsat_related\landsat_auto_download\python\download_landsat_scene.py", line 412, in main
    connect_earthexplorer_no_proxy(usgs)
  File "U:\gis_jinkai\RS_landsat_related\landsat_auto_download\python\download_landsat_scene.py", line 67, in connect_earthexplorer_no_proxy
    data=urllib2.urlopen("https://ers.cr.usgs.gov").read()
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 504: Gateway Timeout

**Comment by olivierhagolle** [comment]
Due to the US government shutdown, the distribution of LANDSAT data had momentary issues at that time.

**Comment by jinkaizhang** [comment]
It is not working now.  I just tried, same error.

python download_landsat_scene.py -z unzip -o scene -u usgs.txt -b LC8 -d
20190710 -f 20190712 --output
X:\2019_projects\Fire_satellite_data\landsat\2019_7_11 -s 047020

None None
Traceback (most recent call last):
  File "download_landsat_scene.py", line 592, in <module>
    main()
  File "download_landsat_scene.py", line 412, in main
    connect_earthexplorer_no_proxy(usgs)
  File "download_landsat_scene.py", line 67, in
connect_earthexplorer_no_proxy
    data=urllib2.urlopen("https://ers.cr.usgs.gov").read()
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 523, in
http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\ArcGISx6410.3\lib\urllib2.py", line 531, in
http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 504: Gateway Timeout
